### ISSUE TITLE
Blue dots not changing colour

### ISSUE THREAD

**Issue by spacem** [maty21/mocha-sidebar#17] opened 2017-11-07 07:03 UTC
Sometimes when tests fail the dots stay blue instead of turning red and after that it seems they don't go green even after fixing the tests until I restart vscode and re-run them.

**Comment by maty21** [comment] 2017-11-07 07:48
Tks do you have sample that I can clone or a specific scenario to reproduce coz I can't reproduce it  in my tests

**Comment by ThatBrianDude** [comment] 2017-11-07 12:31
I get the same behaviour as @spacem described. Its hard to provide samples as the behaviour is not consistent.

**Comment by rosesonfire** [comment] 2017-11-08 07:37
@spacem @ThatBrianDude do any of you have any Mocha hooks like **before**, **beforeEach**, **afterEach**, etc?

**Comment by maty21** [comment] 2017-11-08 08:58
@rosesonfire in my test I'm using hooks and never saw this problem do you have any consistent way to reproduce it ?

**Comment by rosesonfire** [comment] 2017-11-08 09:24
@maty21 I am not sure if this is the same problem, but sounds quite similar. This is the issue I am talking about: #15. It has the sample code that produces a similar bug in my environment.

**Comment by maty21** [comment] 2017-11-09 05:36
@spacem  please try to reproduce it in version 0.12.0 
tks a lot

**Comment by maty21** [comment] 2017-11-11 07:27
@spacem I'm closing the issue feel free to reopen it again if it not fixed for you

**Closed** 2017-11-11 07:27 UTC
Labels: bug, fixed

**Comment by spacem** [comment] 2017-11-13 03:56
Sorry for the delayed response. I don't have hooks and I don't have a sample I can share right now. Just updated to 0.13.2, restarted vscode, ran a single test and the blue circle didn't turn green - but I can see the mocha output window. I'll try sometime to make a little test repository that demonstrates the issue.

In case it helps here is the ouput shown in the mocha tab:
`Running Mocha with Node.js at C:\Program Files\nodejs\node.EXE

Applying Mocha options:
  {
    "compilers": {
      "ts": "ts-node/register"
    }
  }

Test file(s):
  c:\work\project1\project1\criticality\test\criticality-export-route.spec.ts

Grep pattern:
  ^criticality export exports with children$


  criticality export
    √ exports with children


  1 passing (11ms)

###end
------------------------------------
finish failuare amount:0
------------------------------------
debug: found children 2
{
  "passed": [
    {
      "name": "exports with children",
      "fullName": "criticality export exports with children",
      "suitePath": [
        "",
        "criticality export"
      ],
      "file": "c:\\work\\project1\\project1\\criticality\\test\\criticality-export-route.spec.ts"
    }
  ],
  "failed": []
}`
