### ISSUE TITLE
Last Update has an "command 'mocha-maty.refreshExplorer' not found" error

### ISSUE THREAD

**Issue by artsjedi** [maty21/mocha-sidebar#114] opened 2018-06-19 17:01 UTC
### Description

After v0.20.4 update I'm not able to start tests anymore. 

#### Steps to Reproduce
1. Install latest mocha sidebar v 0.20.4 on Windows 10 and VS Code v 1.24.1
2. try to use any of its buttons

#### Expected Results
Buttons working as it is.

#### Actual Results
When click on the play button i got the fallowing error:
> command 'mocha-maty.autoPlayPause' not found

When click on the refresh button I got the fallowing error:
> command 'mocha-maty.refreshExplorer' not found

When click on the coverage button I got the fallowing error:
> command 'mocha-maty.coverage' not found

#### Settings file

    "mocha.requires": ["ts-node/register"],
    "mocha.files.glob": "test/**/*.ts"

### Versions

- VScode: v1.24.1
- Mocha SideBar: v0.20.4
- Node Version: v8.11.1

### OS version

- [X] Windows

- [ ] Mac

- [ ] Linux

**Comment by yehiyam** [comment] 2018-06-19 17:03
Did you try to uninstall the extension and install again? Maybe it a broken
install

**Comment by artsjedi** [comment] 2018-06-19 17:32
Yes I did.

**Comment by kavika-1** [comment] 2018-06-19 17:33
Same here, and uninstall / reinstall did not work (with quitting vscode in between, etc.)

**Comment by jamckelvey** [comment] 2018-06-19 17:33
+1 here too

**Comment by artsjedi** [comment] 2018-06-19 17:52
I made a clean reinstall of VS Code, and im getting the fallowing Error 
![image](https://user-images.githubusercontent.com/2263037/41614983-6dd2a528-73d0-11e8-9c5a-25ebcdb3f7f6.png)

**Comment by maty21** [comment] 2018-06-19 17:54
Sorry of the problem do my best to fix it as fast as I can

**Comment by artsjedi** [comment] 2018-06-19 18:07
How can I use the last stable version?

**Comment by maty21** [comment] 2018-06-19 18:19
Revert to previous version untill I stabilize this one let me know if it's
working for you guys sry for the inconvenient

**Comment by maty21** [comment] 2018-06-19 18:44
@artsjedi  
can you try  to install this extension build please  i cant reproduce it on my pc and i want to verify that its working now on windows tks 

[](https://files.fm/u/mvqxuv23
)

**Comment by jamckelvey** [comment] 2018-06-19 19:08
Still not working on my box (Windows 10). Same problem.

**Comment by maty21** [comment] 2018-06-19 19:28
On which version ?

**Comment by jamckelvey** [comment] 2018-06-19 19:34
The one you posted to files.fm. I also occasionally get that same script error that artsjedi mentioned above but not sure how to repro that. It doesn't always happen.

**Comment by maty21** [comment] 2018-06-19 19:45
That script is happening only on windows cos windows can run js as exe .
And the one from marketplace ?

**Comment by maty21** [comment] 2018-06-19 20:11
Revert in marketplace to old version try now

**Comment by jamckelvey** [comment] 2018-06-19 20:39
I originally experience the problem with the one from the marketplace like artsjedi. Just thought I would try the one you posted above to see if it would help but no luck.

**Comment by jamckelvey** [comment] 2018-06-19 21:39
sure, let me know when you have an updated versions and I'll give it a go.

**Comment by maty21** [comment] 2018-06-19 21:39
already updated version 0.12.5
Maty Z

**Comment by kavika-1** [comment] 2018-06-19 21:47
ok working again for me 0.20.5

**Comment by jamckelvey** [comment] 2018-06-19 21:47
Oh sorry, thought you had a fix you wanted me to test. The one in the marketplace is working fine.

**Comment by maty21** [comment] 2018-06-19 22:11
tks guys 

just create a fix for windows will appreciate if you can install it and verify that it works ok 
[https://files.fm/u/bv7r2q6b](https://files.fm/u/bv7r2q6b )
appreciate if can check code coverage feature as well 

tks a lot :)

**Comment by jamckelvey** [comment] 2018-06-19 22:31
Just tried 0.20.6 from the file share, still same problem.

**Comment by maty21** [comment] 2018-06-19 22:44
Tks can you please explain what y doing and add screenshot tks

**Comment by yehiyam** [comment] 2018-06-20 08:21
hi @artsjedi @kavika-1 @jamckelvey @ankon 
I've created a new version (0.20.7). Could you please try it and let us know
We've tested it on ubuntu and two different windows 10 machines, and it seems to be working.
[https://files.fm/u/qsq54k9k](https://files.fm/u/qsq54k9k)
We want to wait for your input before publishing

**Comment by Noldaru** [comment] 2018-06-20 08:47
Same issue here on Mac OSX 10.13.5, using VSCode 1.24.1 with the 0.20.7 version of the extension.

**Comment by maty21** [comment] 2018-06-20 08:50
@Noldaru  can you send a screenshot of what you see/explain what you see in more details.
btw what is your node version

**Comment by Noldaru** [comment] 2018-06-20 09:21
![mocha-sidebar-errors](https://user-images.githubusercontent.com/18631501/41649480-f5d69c58-747b-11e8-864e-adf2d0259f37.png)

**Comment by jamckelvey** [comment] 2018-06-20 13:58
The steps are pretty straightforward:
1. Uninstall the previous mocha sidebar & reload vscode
2. Install another mocha sidebar & reload vscode
3. Click the 'Test' icon in vscode
4. Click on the mocha refresh button to search for tests
5. The error in the screenshot shown above pops up and no tests are shown

FWIW...here is a list of my currently installed extensions in case there are some that aren't playing nice together:
![image](https://user-images.githubusercontent.com/1966532/41662967-533b3cc0-7470-11e8-9bcd-28b8f1743ebf.png)

**Comment by maty21** [comment] 2018-06-20 17:59
hi guys 

our suspicion was that something went wrong during the merge in the package json file, therefore, I merged the file manually again. will appreciate if you could test it again.
thanks a lot for your helping and support 

[https://files.fm/u/rp62f2wz](https://files.fm/u/rp62f2wz)

**Comment by jamckelvey** [comment] 2018-06-20 20:03
Still no-go.
When clicking the mocha refresh button, I get this:
![image](https://user-images.githubusercontent.com/1966532/41681612-1d041f90-74a3-11e8-983d-29d93c3aa087.png)
When clicking the 'Click for coverage' button, I get this:
![image](https://user-images.githubusercontent.com/1966532/41681685-658ffdce-74a3-11e8-8a9c-107f955ed7a8.png)

**Comment by maty21** [comment] 2018-06-20 20:08
What that weird do you have any configuration other than the basic ? If so
can you describe what ? Can you please remove all mocha configuration and
try  again ?

**Comment by jamckelvey** [comment] 2018-06-20 20:45
Ok, we're getting somewhere. I removed my mocha configuration and at least it doesn't pop that error now (but it also doesn't find my tests because of the removed config). Here is what I removed:

  "mocha.files.glob": "server/**/*{.spec.js,.spec-ts.ts}",
  "mocha.env": {
    "NODE_ENV": "test",
    "WEBSTORM": "test",
    "TS_NODE_PROJECT": "tsconfig.server.json"
  },
  "mocha.requires": [
    "ts-node/register"
  ]

**Comment by jamckelvey** [comment] 2018-06-20 20:52
This setting appears to be the culprit:
"mocha.requires": [
    "ts-node/register"
  ]

**Comment by maty21** [comment] 2018-06-20 21:04
Nice :) that's the reason we couldn't reproduce it in our tests I'll try to figure out what makes this happens I have some idea tks man  :)

**Comment by maty21** [comment] 2018-06-21 15:22
think it will be better now can you try this one please 
[https://files.fm/u/vjvd46xf](https://files.fm/u/vjvd46xf)

**Comment by jamckelvey** [comment] 2018-06-21 15:41
Works like champ! Looks like you got it. Thank you so much!

**Comment by maty21** [comment] 2018-06-21 15:43
Nice :) did you managed to check if coverage working for you ?

**Comment by jamckelvey** [comment] 2018-06-21 15:51
I honestly haven't had time to play with that feature yet but I at least don't get error messages when I click the code coverage button

**Comment by maty21** [comment] 2018-06-21 15:53
Ok tks a lot for helping man we couldn't fix it without you :)
Hope you will like the new feature

**Comment by maty21** [comment] 2018-06-22 08:44
Can I close this issue guys ?

**Comment by maty21** [comment] 2018-06-22 12:02
I'm closing it, for now, feel free to reopen it

**Closed** 2018-06-22 12:03 UTC

**Comment by mehrta** [comment] 2021-04-02 16:58
I also get this error in:
VSCode 1.55
Extension version: 0.22.2

![image](https://user-images.githubusercontent.com/34556599/113436617-45f93880-93fa-11eb-91be-3b9ea74f7024.png)
