### ISSUE TITLE
How to run all tests with single trigger.

### ISSUE THREAD

**Issue by rosesonfire** [maty21/mocha-sidebar#13] opened 2017-11-05 19:12 UTC
When I right click on **Tests** and click **run all tests**, I get exception with this stack trace
<pre>Test file(s):
  undefined
module.js:529
    throw err;
    ^

Error: Cannot find module '/home/user/dir1/dir2/dir3/undefined'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.0/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.0/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.0/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.0/worker/runtest.js:57:7)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)<pre>

**Comment by maty21** [comment] 2017-11-05 19:22
Do you have something in this path
'/home/user/dir1/dir2/dir3/undefined
It's seems like that you referencing to wrong path
Is it run successfully when you running mocha from command line

**Comment by rosesonfire** [comment] 2017-11-05 19:27
No I do not have anything in the path '/home/user/dir1/dir2/dir3/undefined'.
The path '/home/user/dir1/dir2/dir3' exists, but the path '/home/user/dir1/dir2/dir3/undefined' does not  exist.'
It runs successfully when I run mocha from command line. 
Also, I can run test suits individually from mocha-sidebar.

**Comment by maty21** [comment] 2017-11-05 19:29
Let me check it again maybe I broke something

**Comment by maty21** [comment] 2017-11-05 22:20
couldn't reproduce it on my pc with my tests , if you can upload not working sample it will be helpful tks

**Comment by rosesonfire** [comment] 2017-11-06 07:27
You can clone/fork the project, and open it in vscode:
[https://github.com/rosesonfire/react-try-out](https://github.com/rosesonfire/react-try-out)

And use this **.vscode/settings.json**
<pre>
{
  "editor.tabSize": 2,
  "mocha.options": {"bail": false, "fullTrace": true, "useColors": true, "useInlineDiffs": true },
  "mocha.files.glob": "dist/**/*.spec.js"
}
</pre>

1. Then run:
<pre>npm install</pre>
2. Then run the tests from command line. This runs successfully:
<pre>npm run test</pre>
3. Then **refresh** the **mocha-sidebar** and the tests should be visible in the **mocha-sidebar**. Right click on the root (i.e. **Tests**) and click **Run all tests**. This triggers the exception in the **output**.
4. However, if you right click on individual tests or test-suites, and click **Run test** or **Run tests from this level**, the corresponding test(s) run successfully.

Let me know if I am doing something wrong here.

**Comment by maty21** [comment] 2017-11-06 08:51
Tks :)

**Comment by maty21** [comment] 2017-11-06 12:04
find the issue 
im creating object tree that represent the suits 
the problem is that im creating object with test property (not the best idea need to change it to uniuqe name)
so for your problem you have test in fronend/index.spec.js 
``` js
describe("test", function () {
});
```
as a workaround change the test to something else

**Comment by rosesonfire** [comment] 2017-11-06 12:28
Thanks, that did the trick! I changed the name of my test from "test" to something else and it is working now.

**Comment by maty21** [comment] 2017-11-07 04:30
please verify that its working for you without the workaround tks :)

**Comment by rosesonfire** [comment] 2017-11-07 05:04
I updated the extension by uninstalling and then reinstalling it in vscode and tried again. I am afraid the exception was thrown again.

<pre>
Test file(s):
  undefined
module.js:529
    throw err;
    ^

Error: Cannot find module '/home/user/dir1/dir2/dir3/undefined'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.14/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.14/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.14/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/user/.vscode/extensions/maty.vscode-mocha-sidebar-0.10.14/worker/runtest.js:57:7)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)

</pre>

**Comment by maty21** [comment] 2017-11-07 05:12
ok let me check it again

**Comment by maty21** [comment] 2017-11-07 10:38
fixed  for version 0.10.16 (checked also in your code :)) 
the problem was that for some reason the code was not published to the marketplace

**Comment by rosesonfire** [comment] 2017-11-08 07:42
I updated Mocha Sidebar again, and it is working fine now. Thanks!

**Comment by maty21** [comment] 2017-11-08 08:50
I'm closing the issue tks

**Closed** 2017-11-08 08:50 UTC
